// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistracijaTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registracijaTest() {
    driver.get("https://spektar.rs/");
    driver.manage().window().setSize(new Dimension(1696, 1026));
    driver.findElement(By.linkText("Prijavi se")).click();
    driver.findElement(By.linkText("Registruj se")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("miloskovacevic889@gmail.com");
    driver.findElement(By.cssSelector(".button > span")).click();
    assertThat(driver.findElement(By.cssSelector(".message")).getText(), is("Link za potvrdu registracije Vam je poslat na email adresu. Proverite svoj email, i završite proces registracije."));
    driver.close();
  }
}
