// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FilterTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filterTest() {
    driver.get("https://spektar.rs/");
    driver.manage().window().setSize(new Dimension(1696, 1026));
    driver.findElement(By.cssSelector(".hover .categories-submenu__list:nth-child(1) span")).click();
    driver.findElement(By.cssSelector(".filter-value > .hover")).click();
    driver.findElement(By.cssSelector(".hover > .iCheck-helper")).click();
    assertThat(driver.findElement(By.cssSelector(".product-box:nth-child(4) .product-box__name")).getText(), is("Monitor Samsung LC24F390FHRXEN 24\\\"/VA,zakrivljen/1920x1080/60Hz/VGA,HDMI/Freesync/VESA/crna"));
    assertThat(driver.findElement(By.cssSelector(".product-box:nth-child(12) .product-box__name")).getText(), is("Monitor SAMSUNG LF22T350FHRXDU 22\\\"/IPS/1920x1080/75Hz/5ms GtG/VGA,HDMI/Freesync/VESA"));
    assertThat(driver.findElement(By.cssSelector(".product-box:nth-child(14) .product-box__name")).getText(), is("Monitor Samsung LF24T350FHUXEN 24\\\"/IPS/1920x1080/75Hz/5ms GtG/VGA,HDMI/Freesync/VESA"));
    driver.close();
  }
}
